server:
  port: 10001

spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.155.4:3306/innovation-daily?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: innovation-daily
    password: c4NBBG8k5nbrjZrn


  redis:
    #Redis服务器地址  此处的host为通过ifconfig命令获取的linux的IP地址
    host: 1.15.155.4
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引(默认为0)
    database: 0
    #Redis连接超时时间(毫秒)
    timeout: 1800000
    #配置Redis连接池
    lettuce:
      pool:
        #Redis连接池的最大连接数(负数表示无限制)
        max-active: 20
        #Redis最大阻塞等待时间(负数表示没有限制)
        max-wait: -1
        #Redis连接池中的最大空闲连接数
        max-idle: 5
        #Redis连接池中的最小空闲连接数
        min-idle: 0
    password: 123456

  mail:
    username: 2728771838@qq.com #申请服务的邮箱，也就是发送邮件的邮箱
    password: kovpofprtymwdgca #刚才申请服务产生的授权码
    host: smtp.qq.com  #默认
    default-encoding: UTF-8  #默认
    properties: #默认
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  # 设置MyBatis-Plus的全局配置
  #  global-config:
  #    db-config:
  #      # 设置实体类所对应的表的统一前缀
  #      table-prefix: t_
  #      # 设置统一的主键生成策略
  #      id-type: auto
  #  # 配置类型别名所对应的包
  type-aliases-package: com.daily.domain
  #  # 扫描通用枚举的
  # 包
  #  type-enums-package: com.interest.enums


